language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
env:
  - FLASK_VERSION=0.8
  - FLASK_VERSION=0.9
  - FLASK_VERSION=0.10.1
install:
  - pip install -r testapp/requirements.txt
  - pip install -I Flask==$FLASK_VERSION
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install Markdown==2.3.1; fi
script:
  - PYTHONPATH=. make -C testapp/ test
matrix:
  allow_failures:
    - python: pypy
  exclude:
    - python: 3.3
      env: FLASK_VERSION=0.8
    - python: 3.3
      env: FLASK_VERSION=0.9
    - python: 3.4
      env: FLASK_VERSION=0.8
    - python: 3.4
      env: FLASK_VERSION=0.9
